### ISSUE TITLE
scrollbar steppers missing running as root

### ISSUE THREAD

**Issue by nilands55s** [geany/geany#1226]
I hate the overlay scrollbars as I find I have to hunt for them, so they are disabled. To over come the missing items that used to come with fallback/flashback Gnome desktop I use 2 sections of code to bring back functionality.
'gtk-widgets.css' 
usually in the Theme section of the current theme

``` css
`/*************
 * scrollbar *
 *************/
.scrollbar,
.scrollbar.vertical {
    -GtkScrollbar-has-backward-stepper: 1;
    -GtkScrollbar-has-forward-stepper: 1;
    -GtkRange-slider-width: 16;
    -GtkRange-stepper-size: 16;
    -GtkRange-stepper-spacing: 0;
    -GtkRange-trough-border: 0;
    -GtkScrollbar-min-slider-length: 30;

    border-radius: 20px;

    border-image: none;
}

.scrollbar.trough,
.scrollbar.trough.vertical {
    border-color: shade (@bg_color, 0.8);
}

.scrollbar.slider,
.scrollbar.slider:hover,
.scrollbar.button,
.scrollbar.slider.vertical,
.scrollbar.slider.vertical:hover,
.scrollbar.button.vertical {
    border-width: 1px;
    border-style: solid;
    border-color: shade (@bg_color, 0.86);
    background-image: -gtk-gradient (linear, left top, right top,
                                     from (shade (#BDE3F0, 1.08)),
                                     color-stop (0.5, #BDE3F0),
                                     to (shade (#BDE3F0, 0.94)));
    box-shadow: inset 1px 0 shade (@bg_color, 1.1),
                inset -1px 0 shade (@bg_color, 1.01),
                inset 0 1px shade (@bg_color, 1.1),
                inset 0 -1px shade (@bg_color, 1.1);
}

.scrollbar.slider.horizontal,
.scrollbar.slider.horizontal:hover,
.scrollbar.button.horizontal {
    background-image: -gtk-gradient (linear, left top, left bottom,
                                     from (shade (#BDE3F0, 1.08)),
                                     color-stop (0.5, #BDE3F0),
                                     to (shade (#BDE3F0, 0.94)));
    box-shadow: inset 1px 0 shade (@bg_color, 1.1),
                inset -1px 0 shade (@bg_color, 1.1),
                inset 0 1px shade (@bg_color, 1.1),
                inset 0 -1px shade (@bg_color, 1.01);
}

/* overlay scrollbar */
OsThumb {
    color: shade (@fg_color, 1.6);
}`
```

and 'gtk.css' 
in the .config/gtk-3.0 section and /gtk-2.0 section

``` css
`/**************
* Scrollbars *
**************/
.scrollbar {
  -GtkScrollbar-has-backward-stepper: 1;
  -GtkScrollbar-has-forward-stepper: 1;
  -GtkRange-slider-width: 16;
  -GtkRange-stepper-size: 16;
  -GtkRange-stepper-spacing: 0;
  -GtkRange-trough-border: 0;
  -GtkScrollbar-min-slider-length: 30;
}`
```

Perhaps I do not know where to put these for Geany?
Thanks James Niland
