### ISSUE TITLE
wrong matched braces in (S)CSS code

### ISSUE THREAD

**Issue by ousia** [geany/geany#2099]
The following CSS code (well, SCSS) is wrong colored for matching braces:

```css
.page-link {
    display: block;
    padding: 5px 10px;

    &:not(:last-child) {
        margin-right: 0;
    }
```

Here is the output in Geany-1.34.1:

![wrong-coloring](https://user-images.githubusercontent.com/203767/53697904-6b0fbd00-3dd6-11e9-9cd1-172d126d308e.png)

BTW, would it be possible that `.scss` are also colored as `.css` files?
